version: 0.2

phases:
  install:
    commands:
      - curl -O https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip
      - unzip terraform_1.8.5_linux_amd64.zip
      - mv terraform /usr/local/bin/

  pre_build:
    commands:
      - terraform init

  build:
    commands:
      - terraform apply -auto-approve tfplan

  post_build:
    commands:
      - echo Infrastructure deployed successfully
